import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { buildSlimContent } from '../shared/build-slim-content.mjs';
import { buildBranchAccessRules } from '../shared/build-branching-content.mjs';

/**
 * Build the AGENTS.md content for OpenAI Codex CLI.
 *
 * Written at higher verbosity than CLAUDE.md — ChatGPT benefits from
 * explicit step-by-step instructions and clear guardrails.
 *
 * @param {string} coreDir - Path to the overlay's core/ directory
 * @param {string} agentDocsDir - Path to the populated agent_docs/ in the target
 * @param {object} overlayConfig - Overlay configuration object
 * @returns {string} AGENTS.md content
 */
function buildAgentsMd(coreDir, agentDocsDir, overlayConfig = {}) {
  const sections = [];

  // ── Header comment ──
  sections.push('<!-- Generated by ai-workflow-overlay. Do not edit directly. -->');
  sections.push('<!-- Edit agent_docs/ files, then run regenerate.mjs to update. -->');
  sections.push('');

  // ── Title ──
  sections.push('# AGENTS.md');
  sections.push('');
  sections.push('This file provides explicit instructions for OpenAI Codex CLI. Follow all sections carefully and in order. Do not skip phases or sections.');
  sections.push('');

  // ── Development Workflow (verbose 4-phase) ──
  sections.push('## IMPORTANT: Development Workflow');
  sections.push('');
  sections.push('Every significant task MUST follow these four phases in order. Do not skip any phase. Do not begin implementation before completing Research and Plan.');
  sections.push('');

  // Phase 1: Research
  sections.push('### Phase 1: Research');
  sections.push('');
  sections.push('Before writing any code, you MUST:');
  sections.push('');
  sections.push('1. Read all relevant files in `agent_docs/` for this task type (see Agent Docs Reference below).');
  sections.push('2. Explore the codebase: find existing implementations, callers, related patterns.');
  sections.push('3. Identify all files that will be affected by the change.');
  sections.push('4. Note any constraints, existing conventions, or architectural decisions.');
  sections.push('5. Save your findings to `docs/research/YYYY-MM-DD-<topic>.md` before continuing.');
  sections.push('');

  // Phase 2: Plan
  sections.push('### Phase 2: Plan');
  sections.push('');
  sections.push('After research is complete, you MUST:');
  sections.push('');
  sections.push('1. Write a step-by-step implementation plan with explicit file paths for every change.');
  sections.push('2. List each file you will create, modify, or delete.');
  sections.push('3. Describe the exact change at each file (function name, interface, logic change).');
  sections.push('4. Identify which tests need to be written or updated.');
  sections.push('5. Save the plan to `docs/plans/YYYY-MM-DD-<feature>.md` before continuing.');
  sections.push('6. Do NOT begin implementation until the plan is saved.');
  sections.push('');

  // Phase 3: Implement
  sections.push('### Phase 3: Implement');
  sections.push('');
  sections.push('With research and plan complete, you MAY:');
  sections.push('');
  sections.push('1. Follow the plan exactly — do not deviate without updating the plan first.');
  sections.push('2. Write tests before or alongside implementation (not after).');
  sections.push('3. Commit using Conventional Commits: `type(scope): description`.');
  sections.push('   - Types: `feat`, `fix`, `chore`, `refactor`, `test`, `docs`');
  sections.push('   - Example: `feat(auth): add JWT refresh token endpoint`');
  sections.push('4. Make commits at logical checkpoints — not one giant commit at the end.');
  sections.push('5. If you discover unexpected complexity, stop and update the plan before continuing.');
  sections.push('');

  // Phase 4: Validate
  sections.push('### Phase 4: Validate');
  sections.push('');
  sections.push('Before declaring the task done, you MUST:');
  sections.push('');
  sections.push('1. Run the linter and fix all errors. Do not suppress warnings without justification.');
  sections.push('2. Run all tests. Every test must pass. Do not skip tests.');
  sections.push('3. Run the build (if applicable). The build must succeed with no errors.');
  sections.push('4. Verify your changes do not break existing functionality.');
  sections.push('5. Create a pull request targeting the correct branch (see Branch Access Rules below).');
  sections.push('');

  // Exemptions
  sections.push('### Exemptions');
  sections.push('');
  sections.push('Bug fixes, lint-only cleanup, and isolated single-file tweaks with no architectural impact may skip directly to Phase 3: Implement. All other tasks require Phases 1–4 in full.');
  sections.push('');

  // ── Core Principles ──
  sections.push('---');
  sections.push('');
  sections.push('## Core Principles');
  sections.push('');
  sections.push('1. **Observe First, Prescribe Never.** Read the existing code before making any change. Find callers. Check what already exists. Do not assume — verify in the code itself. This is non-negotiable.');
  sections.push('2. **Evidence Before Claims.** Do not say "this works" or "tests pass" without actually running the commands and confirming the output. Always show the result.');
  sections.push('3. **Follow Existing Patterns.** Match the naming conventions, file structure, and code style already present in the codebase. Do not introduce new patterns without a documented reason.');
  sections.push('');

  // ── Shared slim content (git conventions, agent docs, doc requirements, guards) ──
  sections.push(buildSlimContent(coreDir, agentDocsDir, overlayConfig));

  // ── Branch Access Rules (reinforced for Codex) ──
  sections.push('---');
  sections.push('');
  sections.push(buildBranchAccessRules(overlayConfig.branchConfig));
  sections.push('');
  sections.push('> **CRITICAL:** Never push directly to protected branches. Always use a feature branch and open a pull request. Violating branch protection rules may cause irreversible damage to the release pipeline.');
  sections.push('');

  // ── Common Mistakes to Avoid ──
  sections.push('---');
  sections.push('');
  sections.push('## Common Mistakes to Avoid');
  sections.push('');
  sections.push('These are the most frequent errors made by AI agents on this codebase. Read carefully.');
  sections.push('');
  sections.push('- **Do not generate placeholder code.** Never write `// TODO: implement`, empty function bodies, or stub implementations unless the plan explicitly calls for a stub. Every function you write must work.');
  sections.push('- **Do not skip reading agent_docs/.** The agent_docs/ directory contains codebase-specific instructions that override generic patterns. Skipping it leads to incorrect implementations.');
  sections.push('- **Do not add unrequested features.** Implement exactly what was asked. Do not add "nice to have" extras, logging, error handling, or refactors that were not part of the task.');
  sections.push('- **Do not push to protected branches.** Never run `git push` directly to `main`, `master`, or any other protected branch. Always open a pull request.');
  sections.push('- **Do not claim tests pass without running them.** Always run the test command and include the output. "I believe the tests pass" is not acceptable.');
  sections.push('- **Do not create new files when existing ones suffice.** Before creating a new utility, module, or helper, search the codebase for an existing one. Prefer extending existing code over adding new files.');
  sections.push('');

  return sections.join('\n') + '\n';
}

// ─── Public API ───────────────────────────────────────────────────────────

/**
 * Generate AGENTS.md for OpenAI Codex CLI at the target project root.
 *
 * @param {string} targetDir - Root directory of the project being onboarded
 * @param {string} coreDir - Path to the overlay's core/ directory
 * @param {string} agentDocsDir - Path to the populated agent_docs/ in the target project
 * @param {object} overlayConfig - Overlay configuration object (detectedStacks, branchConfig, etc.)
 * @returns {string[]} Array containing the path to the generated AGENTS.md file
 */
export function generateCodexConfig(targetDir, coreDir, agentDocsDir, overlayConfig = {}) {
  const content = buildAgentsMd(coreDir, agentDocsDir, overlayConfig);
  const outputPath = join(targetDir, 'AGENTS.md');
  writeFileSync(outputPath, content, 'utf8');
  return [outputPath];
}
