import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { buildSlimContent } from '../shared/build-slim-content.mjs';

/**
 * Generates .github/copilot-instructions.md — a slim reference doc.
 *
 * @param {string} targetDir - The project being onboarded
 * @param {string} coreDir - The overlay's core/ directory
 * @param {string} agentDocsDir - The populated agent_docs/ directory in the target
 * @param {string[]} detectedStacks - Stack identifiers (unused by Copilot, kept for API consistency)
 * @returns {string} Path to the generated file
 */
export function generateCopilotConfig(targetDir, coreDir, agentDocsDir, detectedStacks = []) {
  const sections = [];

  sections.push('<!-- Generated by ai-workflow-overlay. Do not edit directly. -->');
  sections.push('<!-- Edit agent_docs/ files, then run regenerate.mjs to update. -->');
  sections.push('');
  sections.push('# Copilot Instructions');
  sections.push('');

  // Shared slim content
  sections.push(buildSlimContent(coreDir, agentDocsDir));

  // ── Project Structure ──
  sections.push('---');
  sections.push('');
  sections.push('## Project Structure');
  sections.push('');
  sections.push('```');
  sections.push('agent_docs/       # Task-specific instructions (see reference table above)');
  sections.push('docs/');
  sections.push('  research/       # Research and design docs');
  sections.push('  plans/          # Implementation plans');
  sections.push('  decisions/      # Architectural Decision Records');
  sections.push('```');
  sections.push('');
  sections.push('Source tree structure is documented in `agent_docs/service_architecture.md`.');
  sections.push('');

  const output = sections.join('\n');

  const githubDir = join(targetDir, '.github');
  if (!existsSync(githubDir)) {
    mkdirSync(githubDir, { recursive: true });
  }

  const outputPath = join(githubDir, 'copilot-instructions.md');
  writeFileSync(outputPath, output, 'utf8');

  return outputPath;
}
