import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, basename } from 'node:path';

/**
 * Generates .cursorrules from core workflow and populated agent_docs.
 *
 * @param {string} targetDir - The project being onboarded (output destination)
 * @param {string} coreDir - The overlay's core/ directory
 * @param {string} agentDocsDir - The populated agent_docs/ directory in the target project
 * @returns {string} Path to the generated file
 */
export function generateCursorConfig(targetDir, coreDir, agentDocsDir) {
  const workflowPath = join(coreDir, 'workflow.md');
  const workflowContent = readFileSync(workflowPath, 'utf8');

  const sections = [];

  sections.push('# Generated by copilot-workflow-base. Do not edit directly.');
  sections.push('# Re-run the Cursor adapter after editing agent_docs to update this file.');
  sections.push('');
  sections.push(workflowContent.trimEnd());

  if (existsSync(agentDocsDir)) {
    const files = readdirSync(agentDocsDir)
      .filter((f) => f.endsWith('.md'))
      .sort();

    if (files.length > 0) {
      sections.push('');
      sections.push('---');
      sections.push('');
      sections.push('## Agent Documentation');

      for (const file of files) {
        const filePath = join(agentDocsDir, file);
        const content = readFileSync(filePath, 'utf8');
        const title = basename(file, '.md').replace(/_/g, ' ');

        sections.push('');
        sections.push(`### ${title}`);
        sections.push('');
        sections.push(content.trimEnd());
      }
    }
  }

  const output = sections.join('\n') + '\n';

  const outputPath = join(targetDir, '.cursorrules');
  writeFileSync(outputPath, output, 'utf8');

  return outputPath;
}
