#!/usr/bin/env node
/**
 * copilot-workflow-base onboarding script
 *
 * Usage:
 *   node scripts/onboard.mjs
 *   node scripts/onboard.mjs --target /path/to/project
 */

import { createInterface } from 'node:readline';
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync, copyFileSync } from 'node:fs';
import { join, dirname, resolve, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execSync } from 'node:child_process';
import { buildBranchingWorkflow } from '../adapters/shared/build-branching-content.mjs';
import { generateReadmeAgentic } from '../adapters/shared/build-readme-agentic.mjs';

const OVERLAY_ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const CORE_DIR = join(OVERLAY_ROOT, 'core');
const STACKS_DIR = join(OVERLAY_ROOT, 'stacks');

// ─── Helpers ───────────────────────────────────────────────────────────────

function parseTarget() {
  const i = process.argv.indexOf('--target');
  return i !== -1 && process.argv[i + 1] ? resolve(process.argv[i + 1]) : process.cwd();
}

function makeRl() {
  return createInterface({ input: process.stdin, output: process.stdout });
}

function ask(rl, q) {
  return new Promise((res) => rl.question(q, res));
}

const header = (t) => console.log(`\n=== ${t} ===`);
const info   = (t) => console.log(`  ${t}`);
const warn   = (t) => console.log(`  [WARN] ${t}`);
const ok     = (t) => console.log(`  [OK] ${t}`);

function readPkg(dir) {
  const p = join(dir, 'package.json');
  try { return existsSync(p) ? JSON.parse(readFileSync(p, 'utf8')) : null; } catch { return null; }
}

function hasDep(pkg, name) {
  return !!(pkg?.dependencies?.[name] || pkg?.devDependencies?.[name]);
}

function hasExt(dir, ext) {
  if (!existsSync(dir)) return false;
  try { return readdirSync(dir, { recursive: true }).some((f) => typeof f === 'string' && f.endsWith(ext)); }
  catch { return false; }
}

function ensureDir(d) { mkdirSync(d, { recursive: true }); }

function copyIfMissing(src, dest) {
  if (existsSync(src) && !existsSync(dest)) { copyFileSync(src, dest); return true; }
  return false;
}

// ─── Phase 1: Pre-flight ───────────────────────────────────────────────────

function preflight(targetDir) {
  header('Pre-flight Checks');
  try {
    execSync('git rev-parse --is-inside-work-tree', { cwd: targetDir, stdio: 'pipe' });
    ok('Git repository confirmed.');
  } catch {
    console.error('  [ERROR] Not a git repository. Exiting.');
    process.exit(1);
  }
  try {
    const status = execSync('git status --porcelain', { cwd: targetDir, stdio: 'pipe' }).toString().trim();
    if (status) warn('Uncommitted changes detected. Consider committing first.');
    else ok('Working tree is clean.');
  } catch { /* ignore */ }

  return existsSync(join(targetDir, 'agent_docs')) ||
         existsSync(join(targetDir, '.github', 'copilot-instructions.md'));
}

// ─── Phase 2: Stack detection ──────────────────────────────────────────────

export function detectStacks(targetDir) {
  const pkg = readPkg(targetDir);
  const ls  = (d) => existsSync(d) ? readdirSync(d) : [];
  const detected = [];

  if (hasDep(pkg, 'react') || (hasExt(join(targetDir, 'src'), '.tsx') && existsSync(join(targetDir, 'tsconfig.json'))))
    detected.push('react-typescript');

  if (existsSync(join(targetDir, 'wp-config.php')) || existsSync(join(targetDir, 'wp-content')) ||
      (existsSync(join(targetDir, 'style.css')) && existsSync(join(targetDir, 'functions.php'))))
    detected.push('wordpress');

  if (ls(targetDir).some((f) => f.endsWith('.sln')) || hasExt(targetDir, '.csproj') ||
      existsSync(join(targetDir, 'Program.cs')) || hasExt(join(targetDir, 'src'), 'Program.cs'))
    detected.push('dotnet');

  if (existsSync(join(targetDir, 'pyproject.toml')) || existsSync(join(targetDir, 'setup.py')) ||
      existsSync(join(targetDir, 'requirements.txt')) || existsSync(join(targetDir, 'manage.py')))
    detected.push('python');

  return detected;
}

// ─── Phase 3: Agent selection ──────────────────────────────────────────────

async function selectAgents(rl) {
  header('Agent Selection');
  info('GitHub Copilot configuration will be generated by default.');
  console.log('\n  Also generate config for:\n    (1) Claude Code\n    (2) Cursor\n    (3) OpenAI Codex\n    (4) Claude + Codex (recommended)\n    (5) All\n    (6) None\n');
  const ans = (await ask(rl, '  Selection [4]: ')).trim() || '4';
  const agents = ['copilot'];
  if (ans === '1') agents.push('claude');
  if (ans === '2') agents.push('cursor');
  if (ans === '3') agents.push('codex');
  if (ans === '4') agents.push('claude', 'codex');
  if (ans === '5') agents.push('claude', 'cursor', 'codex');
  return agents;
}

async function collectBranchConfig(rl, targetDir) {
  header('Branching Strategy');
  info('Configure how branches map to environments and agent access.');
  console.log('');

  let existingBranches = [];
  try {
    const raw = execSync('git branch -r', { cwd: targetDir, stdio: 'pipe' }).toString().trim();
    existingBranches = raw.split('\n').map(b => b.trim().replace('origin/', '')).filter(b => b && !b.includes('HEAD'));
    if (existingBranches.length) {
      info(`Detected remote branches: ${existingBranches.join(', ')}`);
      console.log('');
    }
  } catch { /* ignore */ }

  const branchesRaw = (await ask(rl, '  What branches does your project use? (comma-separated)\n  > ')).trim();
  const branchNames = branchesRaw.split(',').map(b => b.trim()).filter(Boolean);

  if (!branchNames.length) {
    info('No branches specified. Using default: develop.');
    return {
      branches: [{ name: 'develop', environments: [], agentAccess: 'full' }],
      featurePrefix: 'feature/*',
      defaultTarget: 'develop',
      protected: [],
      agentAllowed: ['feature/*', 'develop'],
    };
  }

  console.log('');
  info('For each branch, what environment does it map to? (comma-separated, or "none")');
  const branches = [];
  for (const name of branchNames) {
    const envRaw = (await ask(rl, `  ${name} → `)).trim();
    const environments = envRaw.toLowerCase() === 'none' || !envRaw
      ? []
      : envRaw.split(',').map(e => e.trim()).filter(Boolean);
    branches.push({ name, environments, agentAccess: 'full' });
  }

  console.log('');
  const allowedRaw = (await ask(rl, '  Which branches can AI agents push to / create PRs for? (comma-separated)\n  > ')).trim();
  const agentAllowed = allowedRaw.split(',').map(b => b.trim()).filter(Boolean);
  if (!agentAllowed.some(b => b.includes('feature'))) {
    agentAllowed.unshift('feature/*');
  }

  console.log('');
  const protectedRaw = (await ask(rl, '  Which branches are protected? (agents must NEVER push to, comma-separated)\n  > ')).trim();
  const protectedBranches = protectedRaw.split(',').map(b => b.trim()).filter(Boolean);

  for (const b of branches) {
    if (protectedBranches.includes(b.name)) {
      b.agentAccess = 'none';
    }
  }

  console.log('');
  const defaultTarget = (await ask(rl, `  Default PR target for feature branches? [${branchNames[0]}]: `)).trim() || branchNames[0];

  return {
    branches,
    featurePrefix: 'feature/*',
    defaultTarget,
    protected: protectedBranches,
    agentAllowed,
  };
}

async function handleSuperpowers(rl) {
  header('Superpowers Plugin');
  info('The superpowers plugin provides a structured 4-phase AI workflow:');
  info('  Brainstorm → Plan → Execute → Complete');
  console.log('');

  const homedir = process.env.HOME || process.env.USERPROFILE || '';
  const pluginDir = join(homedir, '.claude', 'plugins', 'cache', 'claude-plugins-official', 'superpowers');
  const isInstalled = existsSync(pluginDir);

  if (isInstalled) {
    ok('Superpowers plugin is already installed.');
    return true;
  }

  const ans = (await ask(rl, '  Install superpowers for Claude Code? [Y/n]: ')).trim().toLowerCase();
  if (ans === 'n') {
    info('Skipped. You can install later — see README-AGENTIC.md for instructions.');
    return false;
  }

  console.log('');
  info('To install superpowers, run this in Claude Code:');
  console.log('');
  console.log('    /install-plugin superpowers');
  console.log('');
  info('(The onboard script cannot install Claude Code plugins directly.)');
  ok('Superpowers integration noted. Generated files will reference the 4-phase workflow.');
  return true;
}

// ─── Phase 4: CI detection ─────────────────────────────────────────────────

async function detectCI(rl, targetDir) {
  header('CI Detection');
  const hasGHA   = existsSync(join(targetDir, '.github', 'workflows'));
  const hasAzure = existsSync(join(targetDir, 'azure-pipelines.yml'));
  const selection = [];

  if (hasGHA || hasAzure) {
    if (hasGHA)   info('GitHub Actions workflows detected.');
    if (hasAzure) info('Azure DevOps pipeline detected.');
    const ans = (await ask(rl, '  Add quality gates to existing CI? [y/N]: ')).trim().toLowerCase();
    if (ans === 'y') {
      if (hasGHA)   selection.push('github-actions');
      if (hasAzure) selection.push('azure-devops');
    }
  } else {
    info('No CI configuration found.');
    console.log('\n  Set up CI for:\n    (1) GitHub Actions\n    (2) Azure DevOps\n    (3) Both\n    (4) Skip\n');
    const ans = (await ask(rl, '  Selection [4]: ')).trim() || '4';
    if (ans === '1') selection.push('github-actions');
    if (ans === '2') selection.push('azure-devops');
    if (ans === '3') selection.push('github-actions', 'azure-devops');
  }
  return selection;
}

// ─── Phase 5: File generation ──────────────────────────────────────────────

const ALWAYS_DOCS = [
  'building_the_project.md', 'code_conventions.md', 'running_tests.md',
  'service_architecture.md', 'memory_system.md', 'branching_workflow.md',
  'audit_skills.md', 'dependency_updates.md',
];

function getOptionalDocs(targetDir) {
  const pkg = readPkg(targetDir);
  const hasAuth = hasDep(pkg, 'jsonwebtoken') || hasDep(pkg, 'passport') ||
    existsSync(join(targetDir, 'src', 'auth')) || existsSync(join(targetDir, 'src', 'middleware', 'auth.ts'));
  const hasDb   = hasDep(pkg, 'prisma') || hasDep(pkg, '@prisma/client') || hasDep(pkg, 'typeorm') ||
    hasDep(pkg, 'drizzle-orm') || existsSync(join(targetDir, 'prisma')) || existsSync(join(targetDir, 'migrations'));
  const hasFE   = hasDep(pkg, 'react') || hasDep(pkg, 'vue') || existsSync(join(targetDir, 'src', 'components'));
  const hasApi  = hasDep(pkg, 'express') || hasDep(pkg, 'fastify') ||
    existsSync(join(targetDir, 'src', 'routes')) || existsSync(join(targetDir, 'apps', 'api'));

  const optional = {};
  if (hasAuth) optional['authentication.md'] = true;
  if (hasDb)   optional['database_schema.md'] = true;
  if (hasFE)   optional['frontend_quality.md'] = true;
  if (hasFE)   optional['image_optimization.md'] = true;
  if (hasApi)  optional['service_communication.md'] = true;
  if (hasApi)  optional['service_communication_patterns.md'] = true;
  return optional;
}

async function generateFiles(targetDir, overlayConfig, agents, ciSelection) {
  header('File Generation');
  const created = [];

  // a. Docs skeleton
  for (const sub of ['decisions', 'research', 'plans']) {
    const keep = join(targetDir, 'docs', sub, '.gitkeep');
    ensureDir(dirname(keep));
    if (!existsSync(keep)) { writeFileSync(keep, ''); created.push(`docs/${sub}/.gitkeep`); }
  }

  // b. ADR templates
  const decSrc  = join(CORE_DIR, 'docs', 'decisions');
  const decDest = join(targetDir, 'docs', 'decisions');
  if (existsSync(decSrc)) {
    for (const f of readdirSync(decSrc)) {
      if (copyIfMissing(join(decSrc, f), join(decDest, f))) created.push(`docs/decisions/${f}`);
    }
  }

  // c. agent_docs templates
  const agentDocsSrc  = join(CORE_DIR, 'agent_docs');
  const agentDocsDest = join(targetDir, 'agent_docs');
  ensureDir(agentDocsDest);
  const optionalDocs = getOptionalDocs(targetDir);
  for (const f of readdirSync(agentDocsSrc)) {
    if (!f.endsWith('.md')) continue;
    if (ALWAYS_DOCS.includes(f) || optionalDocs[f]) {
      if (copyIfMissing(join(agentDocsSrc, f), join(agentDocsDest, f))) created.push(`agent_docs/${f}`);
    }
  }
  info(`agent_docs/ templates staged.`);

  // Generate dynamic branching_workflow.md if branchConfig is available
  const { branchConfig } = overlayConfig;
  if (branchConfig) {
    const workflowContent = buildBranchingWorkflow(branchConfig);
    if (workflowContent) {
      const workflowPath = join(agentDocsDest, 'branching_workflow.md');
      writeFileSync(workflowPath, workflowContent, 'utf8');
      info('agent_docs/branching_workflow.md generated from branch config.');
    }
  }

  // d-e. Adapter generators
  for (const agent of agents) {
    const genPath = join(OVERLAY_ROOT, 'adapters', agent, 'generate.mjs');
    if (!existsSync(genPath)) continue;
    try {
      const mod = await import(genPath);
      if (agent === 'copilot' && mod.generateCopilotConfig) {
        const paths = mod.generateCopilotConfig(targetDir, CORE_DIR, agentDocsDest, overlayConfig);
        for (const p of paths) created.push(relative(targetDir, p));
        ok(`Copilot: ${paths.length} files generated`);
      } else if (agent === 'claude' && mod.generateClaudeConfig) {
        const r = mod.generateClaudeConfig(targetDir, CORE_DIR, agentDocsDest, overlayConfig);
        for (const p of r.paths) created.push(relative(targetDir, p));
        ok('Claude: CLAUDE.md + .claude/settings.json');
      } else if (agent === 'cursor' && mod.generateCursorConfig) {
        const paths = mod.generateCursorConfig(targetDir, CORE_DIR, agentDocsDest, overlayConfig);
        for (const p of paths) created.push(relative(targetDir, p));
        ok(`Cursor: ${paths.length} files generated`);
      } else if (agent === 'codex' && mod.generateCodexConfig) {
        const paths = mod.generateCodexConfig(targetDir, CORE_DIR, agentDocsDest, overlayConfig);
        for (const p of paths) created.push(relative(targetDir, p));
        ok('Codex: AGENTS.md');
      }
    } catch (e) { warn(`${agent} adapter failed: ${e.message}`); }
  }

  // f. CI templates
  const ciTmplDir = join(OVERLAY_ROOT, 'scripts', 'ci-templates');
  for (const ci of ciSelection) {
    const srcDir = join(ciTmplDir, ci);
    if (!existsSync(srcDir)) continue;
    if (ci === 'github-actions') {
      const destDir = join(targetDir, '.github', 'workflows');
      ensureDir(destDir);
      for (const f of readdirSync(srcDir)) {
        if (copyIfMissing(join(srcDir, f), join(destDir, f))) created.push(`.github/workflows/${f}`);
      }
    } else if (ci === 'azure-devops') {
      const dest = join(targetDir, 'azure-pipelines.yml');
      if (copyIfMissing(join(srcDir, 'azure-pipelines.yml'), dest)) created.push('azure-pipelines.yml');
    }
  }

  return { created, agentDocsDest };
}

// ─── Phase 6: Analysis prompt ──────────────────────────────────────────────

function generatePrompt(targetDir, detectedStacks, agentDocsDest, branchConfig) {
  header('Analysis Prompt');
  const stackList = detectedStacks.join(', ') || 'generic';

  const stackGuidance = detectedStacks.map((s) => {
    const tmpl = join(STACKS_DIR, s, 'templates.md');
    return existsSync(tmpl) ? `### ${s}\n\n${readFileSync(tmpl, 'utf8').trim()}` : '';
  }).filter(Boolean).join('\n\n---\n\n');

  const docsList = existsSync(agentDocsDest)
    ? readdirSync(agentDocsDest).filter((f) => f.endsWith('.md')).map((f) => `- agent_docs/${f}`).join('\n')
    : '';

  const content = `# Project Onboarding Analysis

Run this prompt in your AI agent to populate the agent_docs templates.

## Instructions

You are onboarding an existing project into the copilot-workflow-base system.
Your job is to analyze this project and fill in the {{TODO}} placeholders
in the agent_docs/ templates.

## Detected Stacks: ${stackList}

## Files to Populate

${docsList}

## What to Do

For each file in agent_docs/, read the <!-- ONBOARDING: ... --> comments
and follow their instructions. Replace all {{TODO: ...}} placeholders
with actual values discovered from the project.

Start by reading each agent_docs/ file to understand what each template expects,
then traverse the project files to gather the facts needed to fill them in.

### Stack-Specific Guidance

${stackGuidance || '_No stack-specific guidance available._'}

## Branch Configuration

${branchConfig ? `The following branching strategy was configured during onboarding:
- Feature prefix: \`${branchConfig.featurePrefix}\`
- Default PR target: \`${branchConfig.defaultTarget}\`
- Branches: ${branchConfig.branches.map(b => `\`${b.name}\` (${b.environments.join(', ') || 'no environment'})`).join(', ')}
- Protected: ${branchConfig.protected.join(', ') || 'none'}

Verify this matches what you observe in the repo and refine \`agent_docs/branching_workflow.md\` accordingly.` : 'No branching strategy was configured. Detect the branching strategy from git branches and CI config.'}

## Important Rules

- Document what EXISTS, not what should exist
- If something is absent (no tests, no linter), note that — don't add it
- Follow the project's existing conventions
- Don't suggest changes unless there's a genuine security risk
- After populating all templates, report which files were updated and flag
  any {{TODO}} items you could not resolve due to missing information

## Final Step: Regenerate Instruction Files

After populating all agent_docs/ templates, regenerate the instruction files
(CLAUDE.md, copilot-instructions.md, AGENTS.md, .cursorrules) so they reflect the
populated content:

\`\`\`bash
node scripts/regenerate.mjs --target .
\`\`\`

If the overlay repository is not locally available, you can manually update
the instruction files by copying the relevant sections from the populated
agent_docs/ files.
`;

  const promptPath = join(agentDocsDest, '.onboarding-prompt.md');
  writeFileSync(promptPath, content, 'utf8');
  ok(`Analysis prompt: agent_docs/.onboarding-prompt.md`);
  return promptPath;
}

// ─── Phase 7: Summary ──────────────────────────────────────────────────────

function summary(targetDir, created, detectedStacks) {
  header('Summary');
  if (created.length) {
    console.log('\n  Files created:');
    [...new Set(created)].forEach((f) => console.log(`    + ${f}`));
  }

  const notes = [];
  const pkg = readPkg(targetDir);
  if (!hasDep(pkg, 'vitest') && !hasDep(pkg, 'jest')) notes.push('No test framework detected');
  if (!hasDep(pkg, 'eslint') && !existsSync(join(targetDir, '.phpcs.xml'))) notes.push('No linter detected');
  if (!detectedStacks.length) notes.push('No known stack detected — generic overlay applied');

  if (notes.length) {
    console.log('\n  Observations:');
    notes.forEach((n) => console.log(`    * ${n}`));
  }

  console.log('\n  Next steps:');
  console.log('    1. Open your AI agent (Copilot, Claude, etc.)');
  console.log('    2. Run the analysis prompt at agent_docs/.onboarding-prompt.md');
  console.log('    3. Review the populated agent_docs/');
  console.log('    4. Regenerate instruction files: node scripts/regenerate.mjs --target .');
  console.log('    5. Commit the overlay files\n');
}

// ─── Main ──────────────────────────────────────────────────────────────────

async function main() {
  const targetDir = parseTarget();
  console.log(`\ncopilot-workflow-base onboarding`);
  console.log(`Target: ${targetDir}`);

  const rl = makeRl();

  try {
    // Phase 1: Pre-flight
    const overlayExists = preflight(targetDir);
    if (overlayExists) {
      warn('Overlay already detected (agent_docs/ or copilot-instructions.md found).');
      const ans = (await ask(rl, '  Re-run to update? [y/N]: ')).trim().toLowerCase();
      if (ans !== 'y') { console.log('\n  No changes made.\n'); rl.close(); process.exit(0); }
    }

    // Phase 2: Stack detection
    header('Stack Detection');
    const detectedStacks = detectStacks(targetDir);
    info(detectedStacks.length ? `Detected: ${detectedStacks.join(', ')}` : 'No known stack detected. Applying generic overlay.');
    const confirmStack = (await ask(rl, '\n  Proceed with detected stacks? [Y/n]: ')).trim().toLowerCase();
    if (confirmStack === 'n') { info('Aborted.'); rl.close(); process.exit(0); }

    // Phase 3a: Agent selection
    const agents = await selectAgents(rl);

    // Phase 3b: Branching strategy
    const branchConfig = await collectBranchConfig(rl, targetDir);

    // Phase 3c: Superpowers
    const superpowersInstalled = await handleSuperpowers(rl);

    // Phase 4: CI detection
    const ciSelection = await detectCI(rl, targetDir);

    // Determine CI provider
    let ciProvider = null;
    if (ciSelection.includes('azure-devops')) ciProvider = 'azure-devops';
    else if (ciSelection.includes('github-actions')) ciProvider = 'github-actions';

    // Build overlay config
    const overlayConfig = {
      version: 1,
      detectedStacks,
      branchConfig,
      selectedAgents: agents,
      ciProvider,
      superpowersInstalled,
    };

    rl.close();

    // Phase 5: File generation
    const { created, agentDocsDest } = await generateFiles(targetDir, overlayConfig, agents, ciSelection);

    // Write overlay config
    const configPath = join(agentDocsDest, '.overlay-config.json');
    writeFileSync(configPath, JSON.stringify(overlayConfig, null, 2) + '\n', 'utf8');
    created.push('agent_docs/.overlay-config.json');

    // Generate README-AGENTIC.md
    const readmePath = generateReadmeAgentic(targetDir, overlayConfig);
    created.push(relative(targetDir, readmePath));
    ok('README-AGENTIC.md');

    // Phase 6: Analysis prompt
    const promptPath = generatePrompt(targetDir, detectedStacks, agentDocsDest, branchConfig);
    created.push(relative(targetDir, promptPath));

    // Phase 7: Summary
    summary(targetDir, created, detectedStacks);
  } catch (err) {
    rl.close();
    console.error(`\n[ERROR] ${err.message}`);
    process.exit(1);
  }
}

// Only run main() when executed directly, not when imported
const isMainScript = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMainScript) {
  main();
}
