#!/usr/bin/env node
/**
 * ai-workflow-overlay onboarding script
 *
 * Usage:
 *   node scripts/onboard.mjs
 *   node scripts/onboard.mjs --target /path/to/project
 */

import { createInterface } from 'node:readline';
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync, copyFileSync } from 'node:fs';
import { join, dirname, resolve, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execSync } from 'node:child_process';

const OVERLAY_ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const CORE_DIR = join(OVERLAY_ROOT, 'core');
const STACKS_DIR = join(OVERLAY_ROOT, 'stacks');

// ─── Helpers ───────────────────────────────────────────────────────────────

function parseTarget() {
  const i = process.argv.indexOf('--target');
  return i !== -1 && process.argv[i + 1] ? resolve(process.argv[i + 1]) : process.cwd();
}

function makeRl() {
  return createInterface({ input: process.stdin, output: process.stdout });
}

function ask(rl, q) {
  return new Promise((res) => rl.question(q, res));
}

const header = (t) => console.log(`\n=== ${t} ===`);
const info   = (t) => console.log(`  ${t}`);
const warn   = (t) => console.log(`  [WARN] ${t}`);
const ok     = (t) => console.log(`  [OK] ${t}`);

function readPkg(dir) {
  const p = join(dir, 'package.json');
  try { return existsSync(p) ? JSON.parse(readFileSync(p, 'utf8')) : null; } catch { return null; }
}

function hasDep(pkg, name) {
  return !!(pkg?.dependencies?.[name] || pkg?.devDependencies?.[name]);
}

function hasExt(dir, ext) {
  if (!existsSync(dir)) return false;
  try { return readdirSync(dir, { recursive: true }).some((f) => typeof f === 'string' && f.endsWith(ext)); }
  catch { return false; }
}

function ensureDir(d) { mkdirSync(d, { recursive: true }); }

function copyIfMissing(src, dest) {
  if (existsSync(src) && !existsSync(dest)) { copyFileSync(src, dest); return true; }
  return false;
}

// ─── Phase 1: Pre-flight ───────────────────────────────────────────────────

function preflight(targetDir) {
  header('Pre-flight Checks');
  try {
    execSync('git rev-parse --is-inside-work-tree', { cwd: targetDir, stdio: 'pipe' });
    ok('Git repository confirmed.');
  } catch {
    console.error('  [ERROR] Not a git repository. Exiting.');
    process.exit(1);
  }
  try {
    const status = execSync('git status --porcelain', { cwd: targetDir, stdio: 'pipe' }).toString().trim();
    if (status) warn('Uncommitted changes detected. Consider committing first.');
    else ok('Working tree is clean.');
  } catch { /* ignore */ }

  return existsSync(join(targetDir, 'agent_docs')) ||
         existsSync(join(targetDir, '.github', 'copilot-instructions.md'));
}

// ─── Phase 2: Stack detection ──────────────────────────────────────────────

function detectStacks(targetDir) {
  const pkg = readPkg(targetDir);
  const ls  = (d) => existsSync(d) ? readdirSync(d) : [];
  const detected = [];

  if (hasDep(pkg, 'react') || (hasExt(join(targetDir, 'src'), '.tsx') && existsSync(join(targetDir, 'tsconfig.json'))))
    detected.push('react-typescript');

  if (existsSync(join(targetDir, 'wp-config.php')) || existsSync(join(targetDir, 'wp-content')) ||
      (existsSync(join(targetDir, 'style.css')) && existsSync(join(targetDir, 'functions.php'))))
    detected.push('wordpress');

  if (ls(targetDir).some((f) => f.endsWith('.sln')) || hasExt(targetDir, '.csproj') ||
      existsSync(join(targetDir, 'Program.cs')) || hasExt(join(targetDir, 'src'), 'Program.cs'))
    detected.push('dotnet');

  if (existsSync(join(targetDir, 'pyproject.toml')) || existsSync(join(targetDir, 'setup.py')) ||
      existsSync(join(targetDir, 'requirements.txt')) || existsSync(join(targetDir, 'manage.py')))
    detected.push('python');

  return detected;
}

// ─── Phase 3: Agent selection ──────────────────────────────────────────────

async function selectAgents(rl) {
  header('Agent Selection');
  info('GitHub Copilot configuration will be generated by default.');
  console.log('\n  Also generate config for:\n    (1) Claude Code\n    (2) Cursor\n    (3) Both\n    (4) None\n');
  const ans = (await ask(rl, '  Selection [3]: ')).trim() || '3';
  const agents = ['copilot'];
  if (ans === '1') agents.push('claude');
  if (ans === '2') agents.push('cursor');
  if (ans === '3') agents.push('claude', 'cursor');
  return agents;
}

// ─── Phase 4: CI detection ─────────────────────────────────────────────────

async function detectCI(rl, targetDir) {
  header('CI Detection');
  const hasGHA   = existsSync(join(targetDir, '.github', 'workflows'));
  const hasAzure = existsSync(join(targetDir, 'azure-pipelines.yml'));
  const selection = [];

  if (hasGHA || hasAzure) {
    if (hasGHA)   info('GitHub Actions workflows detected.');
    if (hasAzure) info('Azure DevOps pipeline detected.');
    const ans = (await ask(rl, '  Add quality gates to existing CI? [y/N]: ')).trim().toLowerCase();
    if (ans === 'y') {
      if (hasGHA)   selection.push('github-actions');
      if (hasAzure) selection.push('azure-devops');
    }
  } else {
    info('No CI configuration found.');
    console.log('\n  Set up CI for:\n    (1) GitHub Actions\n    (2) Azure DevOps\n    (3) Both\n    (4) Skip\n');
    const ans = (await ask(rl, '  Selection [4]: ')).trim() || '4';
    if (ans === '1') selection.push('github-actions');
    if (ans === '2') selection.push('azure-devops');
    if (ans === '3') selection.push('github-actions', 'azure-devops');
  }
  return selection;
}

// ─── Phase 5: File generation ──────────────────────────────────────────────

const ALWAYS_DOCS = [
  'building_the_project.md', 'code_conventions.md', 'running_tests.md',
  'service_architecture.md', 'memory_system.md', 'branching_workflow.md',
  'audit_skills.md', 'dependency_updates.md',
];

function getOptionalDocs(targetDir) {
  const pkg = readPkg(targetDir);
  const hasAuth = hasDep(pkg, 'jsonwebtoken') || hasDep(pkg, 'passport') ||
    existsSync(join(targetDir, 'src', 'auth')) || existsSync(join(targetDir, 'src', 'middleware', 'auth.ts'));
  const hasDb   = hasDep(pkg, 'prisma') || hasDep(pkg, '@prisma/client') || hasDep(pkg, 'typeorm') ||
    hasDep(pkg, 'drizzle-orm') || existsSync(join(targetDir, 'prisma')) || existsSync(join(targetDir, 'migrations'));
  const hasFE   = hasDep(pkg, 'react') || hasDep(pkg, 'vue') || existsSync(join(targetDir, 'src', 'components'));
  const hasApi  = hasDep(pkg, 'express') || hasDep(pkg, 'fastify') ||
    existsSync(join(targetDir, 'src', 'routes')) || existsSync(join(targetDir, 'apps', 'api'));

  const optional = {};
  if (hasAuth) optional['authentication.md'] = true;
  if (hasDb)   optional['database_schema.md'] = true;
  if (hasFE)   optional['frontend_quality.md'] = true;
  if (hasFE)   optional['image_optimization.md'] = true;
  if (hasApi)  optional['service_communication.md'] = true;
  if (hasApi)  optional['service_communication_patterns.md'] = true;
  return optional;
}

async function generateFiles(targetDir, detectedStacks, agents, ciSelection) {
  header('File Generation');
  const created = [];

  // a. Docs skeleton
  for (const sub of ['decisions', 'research', 'plans']) {
    const keep = join(targetDir, 'docs', sub, '.gitkeep');
    ensureDir(dirname(keep));
    if (!existsSync(keep)) { writeFileSync(keep, ''); created.push(`docs/${sub}/.gitkeep`); }
  }

  // b. ADR templates
  const decSrc  = join(CORE_DIR, 'docs', 'decisions');
  const decDest = join(targetDir, 'docs', 'decisions');
  if (existsSync(decSrc)) {
    for (const f of readdirSync(decSrc)) {
      if (copyIfMissing(join(decSrc, f), join(decDest, f))) created.push(`docs/decisions/${f}`);
    }
  }

  // c. agent_docs templates
  const agentDocsSrc  = join(CORE_DIR, 'agent_docs');
  const agentDocsDest = join(targetDir, 'agent_docs');
  ensureDir(agentDocsDest);
  const optionalDocs = getOptionalDocs(targetDir);
  for (const f of readdirSync(agentDocsSrc)) {
    if (!f.endsWith('.md')) continue;
    if (ALWAYS_DOCS.includes(f) || optionalDocs[f]) {
      if (copyIfMissing(join(agentDocsSrc, f), join(agentDocsDest, f))) created.push(`agent_docs/${f}`);
    }
  }
  info(`agent_docs/ templates staged.`);

  // d-e. Adapter generators
  for (const agent of agents) {
    const genPath = join(OVERLAY_ROOT, 'adapters', agent, 'generate.mjs');
    if (!existsSync(genPath)) continue;
    try {
      const mod = await import(genPath);
      if (agent === 'copilot' && mod.generateCopilotConfig) {
        const out = mod.generateCopilotConfig(targetDir, CORE_DIR, agentDocsDest);
        created.push(relative(targetDir, out));
        ok(`Copilot: ${relative(targetDir, out)}`);
      } else if (agent === 'claude' && mod.generateClaudeConfig) {
        const r = mod.generateClaudeConfig(targetDir, CORE_DIR, agentDocsDest, detectedStacks);
        created.push(relative(targetDir, r.claudeMdPath), relative(targetDir, r.settingsPath));
        ok(`Claude: CLAUDE.md + .claude/settings.json`);
      } else if (agent === 'cursor' && mod.generateCursorConfig) {
        const out = mod.generateCursorConfig(targetDir, CORE_DIR, agentDocsDest);
        created.push(relative(targetDir, out));
        ok(`Cursor: ${relative(targetDir, out)}`);
      }
    } catch (e) { warn(`${agent} adapter failed: ${e.message}`); }
  }

  // f. CI templates
  const ciTmplDir = join(OVERLAY_ROOT, 'scripts', 'ci-templates');
  for (const ci of ciSelection) {
    const srcDir = join(ciTmplDir, ci);
    if (!existsSync(srcDir)) continue;
    if (ci === 'github-actions') {
      const destDir = join(targetDir, '.github', 'workflows');
      ensureDir(destDir);
      for (const f of readdirSync(srcDir)) {
        if (copyIfMissing(join(srcDir, f), join(destDir, f))) created.push(`.github/workflows/${f}`);
      }
    } else if (ci === 'azure-devops') {
      const dest = join(targetDir, 'azure-pipelines.yml');
      if (copyIfMissing(join(srcDir, 'azure-pipelines.yml'), dest)) created.push('azure-pipelines.yml');
    }
  }

  return { created, agentDocsDest };
}

// ─── Phase 6: Analysis prompt ──────────────────────────────────────────────

function generatePrompt(targetDir, detectedStacks, agentDocsDest) {
  header('Analysis Prompt');
  const stackList = detectedStacks.join(', ') || 'generic';

  const stackGuidance = detectedStacks.map((s) => {
    const tmpl = join(STACKS_DIR, s, 'templates.md');
    return existsSync(tmpl) ? `### ${s}\n\n${readFileSync(tmpl, 'utf8').trim()}` : '';
  }).filter(Boolean).join('\n\n---\n\n');

  const docsList = existsSync(agentDocsDest)
    ? readdirSync(agentDocsDest).filter((f) => f.endsWith('.md')).map((f) => `- agent_docs/${f}`).join('\n')
    : '';

  const content = `# Project Onboarding Analysis

Run this prompt in your AI agent to populate the agent_docs templates.

## Instructions

You are onboarding an existing project into the ai-workflow-overlay system.
Your job is to analyze this project and fill in the {{TODO}} placeholders
in the agent_docs/ templates.

## Detected Stacks: ${stackList}

## Files to Populate

${docsList}

## What to Do

For each file in agent_docs/, read the <!-- ONBOARDING: ... --> comments
and follow their instructions. Replace all {{TODO: ...}} placeholders
with actual values discovered from the project.

Start by reading each agent_docs/ file to understand what each template expects,
then traverse the project files to gather the facts needed to fill them in.

### Stack-Specific Guidance

${stackGuidance || '_No stack-specific guidance available._'}

## Important Rules

- Document what EXISTS, not what should exist
- If something is absent (no tests, no linter), note that — don't add it
- Follow the project's existing conventions
- Don't suggest changes unless there's a genuine security risk
- After populating all templates, report which files were updated and flag
  any {{TODO}} items you could not resolve due to missing information
`;

  const promptPath = join(agentDocsDest, '.onboarding-prompt.md');
  writeFileSync(promptPath, content, 'utf8');
  ok(`Analysis prompt: agent_docs/.onboarding-prompt.md`);
  return promptPath;
}

// ─── Phase 7: Summary ──────────────────────────────────────────────────────

function summary(targetDir, created, detectedStacks) {
  header('Summary');
  if (created.length) {
    console.log('\n  Files created:');
    [...new Set(created)].forEach((f) => console.log(`    + ${f}`));
  }

  const notes = [];
  const pkg = readPkg(targetDir);
  if (!hasDep(pkg, 'vitest') && !hasDep(pkg, 'jest')) notes.push('No test framework detected');
  if (!hasDep(pkg, 'eslint') && !existsSync(join(targetDir, '.phpcs.xml'))) notes.push('No linter detected');
  if (!detectedStacks.length) notes.push('No known stack detected — generic overlay applied');

  if (notes.length) {
    console.log('\n  Observations:');
    notes.forEach((n) => console.log(`    * ${n}`));
  }

  console.log('\n  Next steps:');
  console.log('    1. Open your AI agent (Copilot, Claude, etc.)');
  console.log('    2. Run the analysis prompt at agent_docs/.onboarding-prompt.md');
  console.log('    3. Review the populated agent_docs/');
  console.log('    4. Commit the overlay files\n');
}

// ─── Main ──────────────────────────────────────────────────────────────────

async function main() {
  const targetDir = parseTarget();
  console.log(`\nai-workflow-overlay onboarding`);
  console.log(`Target: ${targetDir}`);

  const rl = makeRl();

  try {
    // Phase 1
    const overlayExists = preflight(targetDir);
    if (overlayExists) {
      warn('Overlay already detected (agent_docs/ or copilot-instructions.md found).');
      const ans = (await ask(rl, '  Re-run to update? [y/N]: ')).trim().toLowerCase();
      if (ans !== 'y') { console.log('\n  No changes made.\n'); rl.close(); process.exit(0); }
    }

    // Phase 2
    header('Stack Detection');
    const detectedStacks = detectStacks(targetDir);
    info(detectedStacks.length ? `Detected: ${detectedStacks.join(', ')}` : 'No known stack detected. Applying generic overlay.');
    const confirmStack = (await ask(rl, '\n  Proceed with detected stacks? [Y/n]: ')).trim().toLowerCase();
    if (confirmStack === 'n') { info('Aborted.'); rl.close(); process.exit(0); }

    // Phase 3
    const agents = await selectAgents(rl);

    // Phase 4
    const ciSelection = await detectCI(rl, targetDir);
    rl.close();

    // Phase 5
    const { created, agentDocsDest } = await generateFiles(targetDir, detectedStacks, agents, ciSelection);

    // Phase 6
    const promptPath = generatePrompt(targetDir, detectedStacks, agentDocsDest);
    created.push(relative(targetDir, promptPath));

    // Phase 7
    summary(targetDir, created, detectedStacks);
  } catch (err) {
    rl.close();
    console.error(`\n[ERROR] ${err.message}`);
    process.exit(1);
  }
}

main();
